### ISSUE TITLE
Generate an image out of the grid?

### ISSUE THREAD

**Issue by srameshr** [sivarajng/react-native-photo-grid-frame#2]
Is it possible to make a "collage" out of the created grid? I mean, can the grid be transformed into an actual photo file object?

**Comment by sivarajng** [comment]
Hi Ramesh,
Thanks for your interest. Am not sure about the possibility of Image Collage generator natively in react-native as it involves different stuffs, Am closing this request as it's out of scope for this package which is a gallery viewer.However if possible will check this feature request as a separate repo.
